import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { detectBoilerplate, detectDuplicates, detectVerboseContent, detectStaleReferences, analyzeContent } from '../../src/core/content-analyzer.js';

describe('ContentAnalyzer', () => {
  describe('detectBoilerplate', () => {
    it('detects MIT license boilerplate', () => {
      const content = `// Copyright (c) 2024 TestCorp\n// MIT License\n// Permission is hereby granted`;
      const findings = detectBoilerplate(content, 'test.ts');
      assert.ok(findings.some(f => f.type === 'boilerplate'));
    });
    it('detects auto-generated comments', () => {
      const content = `// Auto-generated by OpenAPI generator\nconst api = {};`;
      assert.ok(detectBoilerplate(content, 'api.ts').length > 0);
    });
    it('returns empty for clean code', () => {
      assert.strictEqual(detectBoilerplate(`const x = 42;\nconsole.log(x);`, 'test.ts').length, 0);
    });
    it('includes file path in findings', () => {
      const findings = detectBoilerplate('// Auto-generated', 'src/test.ts');
      assert.strictEqual(findings[0].file, 'src/test.ts');
    });
  });

  describe('detectDuplicates', () => {
    it('finds identical content across files', () => {
      const shared = 'VERY_LONG_SHARED_CONSTANT_VALUE_FOR_TESTING_WITH_PADDING = 12345';
      const files = [
        { path: 'a.ts', content: shared },
        { path: 'b.ts', content: shared },
        { path: 'c.ts', content: 'const somethingElse = 42;' },
      ];
      const groups = detectDuplicates(files);
      assert.ok(groups.length > 0, 'should find at least one duplicate group');
    });
    it('does not report single occurrence as duplicate', () => {
      const groups = detectDuplicates([{ path: 'unique.ts', content: 'const UNIQUE_LINE_ONLY_IN_THIS_FILE_12345 = 1;' }]);
      assert.strictEqual(groups.length, 0);
    });
    it('returns file list for each group', () => {
      const shared = 'ANOTHER_UNIQUE_SHARED_LINE_FOR_DUPLICATE_TESTING = true';
      const groups = detectDuplicates([
        { path: 'x.ts', content: shared },
        { path: 'y.ts', content: shared },
      ]);
      if (groups.length > 0) {
        assert.ok(groups[0].files.length >= 2);
        assert.ok(groups[0].tokenCount > 0);
      }
    });
  });

  describe('detectVerboseContent', () => {
    it('detects long comment blocks', () => {
      const content = Array(12).fill('// A long comment line for testing verbose detection').join('\n');
      const findings = detectVerboseContent(content, 'verbose.ts');
      assert.ok(findings.some(f => f.type === 'verbose'));
    });
    it('ignores short comment blocks', () => {
      const content = Array(3).fill('// Short comment').join('\n');
      assert.strictEqual(detectVerboseContent(content, 'test.ts').length, 0);
    });
    it('handles code without comments', () => {
      assert.strictEqual(detectVerboseContent('const x = 42;', 'test.ts').length, 0);
    });
  });

  describe('detectStaleReferences', () => {
    it('detects workarounds in TODOs', () => {
      const content = '// TODO this is a workaround until we fix the real issue';
      const findings = detectStaleReferences(content, 'test.ts');
      assert.ok(findings.some(f => f.message.includes('Workaround')));
    });
    it('detects empty TODOs', () => {
      const findings = detectStaleReferences('// TODO:', 'test.ts');
      assert.ok(findings.some(f => f.message.includes('Empty')));
    });
    it('returns empty for clean code', () => {
      assert.strictEqual(detectStaleReferences('const x = 42;', 'test.ts').length, 0);
    });
    it('detects dated TODOs', () => {
      const content = '// TODO fix this before January 2024 - we need to refactor';
      const findings = detectStaleReferences(content, 'test.ts');
      assert.ok(findings.some(f => f.message.includes('Dated')));
    });
    it('distinguishes repeated dated TODOs by source line', () => {
      const todo = '// TODO fix this before January 2024 - we need to refactor';
      const findings = detectStaleReferences(`${todo}\nconst active = true;\n${todo}`, 'test.ts');

      assert.deepStrictEqual(findings.map(f => f.line), [1, 3]);
      assert.strictEqual(findings.length, 2);
      assert.notStrictEqual(`${findings[0].file}:${findings[0].line}`, `${findings[1].file}:${findings[1].line}`);
    });
  });

  describe('analyzeContent', () => {
    it('generates a complete report', () => {
      const files = [
        { path: 'a.ts', content: 'const x = 42;', tokens: 10, language: 'typescript' },
        { path: 'b.ts', content: 'const y = 100;', tokens: 10, language: 'typescript' },
      ];
      const report = analyzeContent(files, 20);
      assert.ok(report.totalTokens === 20);
      assert.ok(Array.isArray(report.findings));
      assert.ok(Array.isArray(report.fileBreakdown));
      assert.ok(Array.isArray(report.suggestions));
      assert.ok(Array.isArray(report.duplicateGroups));
    });
    it('sorts findings by severity', () => {
      const shared = 'VERY_LONG_DUPLICATE_LINE_FOR_TESTING_SEVERITY_ORDER = 999';
      const files = [
        { path: 'a.ts', content: '// Auto-generated by tool\n' + shared, tokens: 15, language: 'typescript' },
        { path: 'b.ts', content: '// Auto-generated by tool\n' + shared, tokens: 15, language: 'typescript' },
      ];
      const report = analyzeContent(files, 30);
      if (report.findings.length >= 2) {
        const sevOrder = { high: 0, medium: 1, low: 2 };
        for (let i = 1; i < report.findings.length; i++) {
          assert.ok(sevOrder[report.findings[i].severity] >= sevOrder[report.findings[i - 1].severity]);
        }
      }
    });
    it('calculates file percentages correctly', () => {
      const files = [
        { path: 'big.ts', content: 'x'.repeat(500), tokens: 500, language: 'typescript' },
        { path: 'small.ts', content: 'x'.repeat(100), tokens: 100, language: 'typescript' },
      ];
      const report = analyzeContent(files, 600);
      const bigFile = report.fileBreakdown.find(f => f.path === 'big.ts');
      const smallFile = report.fileBreakdown.find(f => f.path === 'small.ts');
      if (bigFile && smallFile) assert.ok(bigFile.percentage > smallFile.percentage);
    });
    it('generates suggestions when findings exist', () => {
      const shared = 'VERY_LONG_UNIQUE_DUPLICATE_FOR_SUGGESTION_GENERATION_TEST = 42';
      const files = [
        { path: 'd1.ts', content: '// Auto-generated by tool\n' + shared, tokens: 20, language: 'typescript' },
        { path: 'd2.ts', content: '// Auto-generated by tool\n' + shared, tokens: 20, language: 'typescript' },
      ];
      const report = analyzeContent(files, 40);
      assert.ok(report.findings.length > 0);
    });
  });
});
